import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from "next/router";
import { Box, Button, Center, Stack, Flex } from "@chakra-ui/react"
import { Avatar, AvatarBadge, AvatarGroup } from '@chakra-ui/react'

export default function Home() {
const router = useRouter();
const tosignup = ()=>{
  router.push('/Signup')
 }
 const tologin = ()=>{
  router.push('/Login')
 }

  return (
    <>
      <Head>
        <title>Signup App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <div>
      <Center
        h="100vh"
        bgColor="gray.900">
        <Stack
          align="center"
          bgColor="whiteAlpha.100"
          rounded="3xl"
          spacing={3}
          p={20}
        >

          <Flex
            bgColor="whiteAlpha.800" boxShadow="md" color="gray.900" w="fit-content" borderRadius="lg" p={3} m={1}>
            <h1>Welcome to my page</h1>
          </Flex>
         <br/>
         <br/>
         <br/>
         <br/>

          
          <Button boxShadow="md" onClick={tosignup} >See our signAPP</Button>
          <Button boxShadow="md" onClick={tologin} >See our loginAPP</Button>



        </Stack>

      </Center>
    </div>
      </main>
    </>
  )
}
